version: 3

# silent: true

tasks:
  up:
    cmds:
      - npm i
      - docker compose -f docker-compose.dev.yml up -d
      - npm run dev
    aliases: [default]
  down: docker compose -f docker-compose.dev.yml down