version: 3

# silent: true

tasks:
  up:
    cmds:
      - yarn
      - docker compose -f docker-compose.dev.yml up -d
      - yarn dev
    aliases: [default]
  down: docker compose -f docker-compose.dev.yml down